server:
  port: 8888
#压缩nas备份目录   auto.compress 代表是否启用定时任务处理前一天的（1 启用 0 关闭）,time 为时间
compress:
  bound: 500
auto:
  compress: 1
  time: 0 0 20 * * ?
nas:
  srcPath: /home/video-compress-test/nas/
  bakPath: /home/video-compress-test/nas-bak/
